### ISSUE TITLE
Linux build at windows

### ISSUE THREAD

**Issue by AN3Orik** [Bearwaves/eos4j#1]
Hi.
When i trying to build jni wrapper for Linux i got this error:

```
[exec] C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lEOSSDK-Linux-Shipping: No such file or directory
[exec] collect2.exe: error: ld returned 1 exit status
```

When path to EOS so lib changed to:
```
add(Linux, x64) {
        libraries += file("./jni/EOS/SDK/Bin").absolutePath + "\\libEOSSDK-Linux-Shipping.so"
    }
```

I got this error about wrong lib format

```
[exec] C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\User\Downloads\eos4j-master\eos4j-master\jni\EOS\SDK\Bin\libEOSSDK-Linux-Shipping.so: error adding symbols: file in wrong format
[exec] collect2.exe: error: ld returned 1 exit status
```

Is it possible to build *nix wrapper for Windows or i should use Linux MinGW compiler?
Ty in advance.

**Comment by JoelOtter** [comment]
Hey there, thanks for trying eos4j. :) 

I’m not really an expert in mingw - what you’re attempting _should_ be possible, as far as I know, though I know you might sometimes run into issues trying to link against a library built against a different GCC than the one mingw-w64 uses. 

Could I ask what it is you’re trying to do? You shouldn’t need to run jnigen yourself as part of regular usage - the shared libraries usually get loaded by the JVM at runtime. Is there something you’re trying to change?

**Comment by AN3Orik** [comment]
Ty for answer, seems like my MinGW version has windows only compiler. For now i just trying to make things works, but in future planning to use for wrapping anti-cheat interface for using at java server  instead my current external C# implementation.

**Comment by AN3Orik** [comment]
I tried all possible  mingw  builds (UCRT/MSVCRT +  POSIX/MCF) and no success. 

Still has wrong format  error  for *Nix build (Windows build is ok):
```
> Task :jnigenBuildLinux64
Executing '[ant.bat, -f, C:\Users\User\Downloads\eos4j-master\eos4j-master\jni\build-linux64.xml, -Drelease=true, clean, postcompile, ]'

    [apply] Applied g++.exe to 10 files and 0 directories.
    [apply] Applied gcc.exe to 1 file and 0 directories.

link:
     [exec] C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\User\Downloads\eos4j-master\eos4j-master\jni\EOS\SDK\Bin\libEOSSDK-Linux-Shipping.so: error adding symbols: file in wrong format
     [exec] collect2.exe: error: ld returned 1 exit status

BUILD FAILED
C:\Users\User\Downloads\eos4j-master\eos4j-master\jni\build-linux64.xml:161: exec returned: 1
```

Can you check MinGW version you built release for Win/Nix/Mac?

**Comment by JoelOtter** [comment]
We use minGW to build for Windows from Linux, rather than the other way around. You can see the config here:

https://github.com/Bearwaves/eos4j/blob/master/.github/workflows/publish.yaml

We use the mingw-w64 from the Ubuntu repo, so 8.0.0.

**Comment by AN3Orik** [comment]
Ah, you building via Git Workflows, not via cross-platform compiler. Thanks for answer!
