### ISSUE TITLE
Create minimal example

### ISSUE THREAD

**Issue by dkoding** [Bearwaves/eos4j#2]
Could you please provide a minimal example where you log in and unlock an achievement for the currently logged in Epic Games user.

This is how far I have gotten:

```
eosPlatform.getConnectHandle().login(
new EOSConnect.LoginOptions(new EOSConnect.Credentials(EOS.ExternalCredentialType.EPIC, "???"), 
new EOSConnect.UserLoginInfo("???")), data -> productUserId = data.localUserId);

```
... to get the productUserId. I assume I don't have to create a login screen for my game to unlock achievements but can get the default logged in Epic Games Launcher user? However it is not clear from the documentation how this can be done. I think 95% of the users of this library would benefit from an explanation of this.

**Comment by dkoding** [comment]
It is also unclear where the EOSSDK-Win64-Shipping.dll should be placed,    Library.loadSystem("com.bearwaves.eos4j", "EOSSDK-Win64-Shipping"); is unable to find the .dll file no matter where I put it...

**Comment by JoelOtter** [comment]
Hey, thanks for reporting. I assume you're already using Epic's documentation - eos4j is designed in such a way that their documentation should explain everything and it should work in pretty much the same way.

I'm going to rename this issue to be about the example, because I do want to do that, but I'll try and answer your questions here too.

> I assume I don't have to create a login screen for my game to unlock achievements but can get the default logged in Epic Games Launcher user? However it is not clear from the documentation how this can be done.

This is documented [here](https://dev.epicgames.com/docs/epic-account-services/auth/auth-interface#epic-games-launcher). Essentially the launcher will pass a code to your application as a command-line argument and you use that to log in via the Auth interface. You then get a token from that and use it to log in to Connect, after which you can unlock achievements using a Product User ID, which the Connect interface can give you. I recommend looking at Epic's examples, included in the SDK - they're in C++, but it should be easy enough to see which calls are needed and find the matching Java ones.

Here's a brief sample from my own game. It's not something you'll be able to lift verbatim, probably, but it should show the flow well enough until I can get a proper example together.

```java
private void doCreateEOSInterfaces() {
        try {
            eosPlatform = new EOSPlatform(new EOSPlatform.Options(
                    epicVars.productId, epicVars.sandboxId, epicVars.deploymentId, epicVars.clientId, epicVars.clientSecret,
                    EOSPlatform.Flag.WINDOWS_ENABLE_OVERLAY_OPENGL.getValue()
            ));
        } catch (EOSException e) {
            Gdx.app.error("EpicPlatformManager", "Failed to create EOS Platform interface", e);
            return;
        }

        try {
            eosAuth = eosPlatform.getAuthHandle();
        } catch (EOSException e) {
            Gdx.app.error("EpicPlatformManager", "Failed to get EOS Auth handle", e);
            return;
        }

        try {
            eosConnect = eosPlatform.getConnectHandle();
        } catch (EOSException e) {
            Gdx.app.error("EpicPlatformManager", "Failed to get EOS Connect handle", e);
            return;
        }

        doEpicAuthLogin();

        try {
            eosStats = eosPlatform.getStatsHandle();
        } catch (EOSException e) {
            Gdx.app.error("EpicPlatformManager", "Failed to get EOS Stats handle");
            return;
        }

        try {
            eosAchievements = eosPlatform.getAchievementsHandle();
        } catch (EOSException e) {
            Gdx.app.error("EpicPlatformManager", "Failed to get EOS Achievements handle");
        }
    }

    private void doEpicAuthLogin() {
        eosAuth.login(new EOSAuth.LoginOptions(
                authToken == null ?
                        exchangeCode == null ?
                                new EOSAuth.Credentials(EOS.LoginCredentialType.DEVELOPER, "localhost:1245", "feud") :
                                new EOSAuth.Credentials(EOS.LoginCredentialType.EXCHANGE_CODE, null, exchangeCode) :
                        new EOSAuth.Credentials(EOS.LoginCredentialType.REFRESH_TOKEN, null, authToken.getRefreshToken()),
                0
        ), data -> {
            try {
                EOS.throwIfErrorCode(data.resultCode);
            } catch (EOSException e) {
                Gdx.app.error("EpicPlatformManager", "Auth login failed", e);
                loginState = LoginState.FAILED;
                return;
            }
            Gdx.app.log("EpicPlatformManager", "Login success");
            try {
                idToken = eosAuth.copyIdToken(data.selectedAccountId);
            } catch (EOSException e) {
                Gdx.app.error("EpicPlatformManager", "Failed to copy id token", e);
                loginState = LoginState.FAILED;
                return;
            }
            if (authToken != null) {
                authToken.release();
            }
            if (eosPlatformOld != null) {
                eosPlatformOld.release();
                eosPlatformOld = null;
            }
            try {
                authToken = eosAuth.copyUserAuthToken(data.selectedAccountId);
            } catch (EOSException e) {
                Gdx.app.error("EpicPlatformManager", "Failed to copy user auth token", e);
                loginState = LoginState.FAILED;
                return;
            }
            Gdx.app.debug("EpicPlatformManager", "Got ID token: " + idToken.getJsonWebToken());
            doConnectLogin();
        });
    }

    private void doConnectLogin() {
        eosConnect.login(new EOSConnect.LoginOptions(new EOSConnect.Credentials(EOS.ExternalCredentialType.EPIC_ID_TOKEN, idToken.getJsonWebToken()), null), loginCallbackInfo -> {
            if (loginCallbackInfo.resultCode == EOSResultCode.INVALID_USER.getValue()) {
                // Invalid user - needs to be created
                Gdx.app.log("EpicPlatformManager", "Creating user");
                eosConnect.createUser(loginCallbackInfo.continuanceToken, createUserCallbackInfo -> doHandleConnectCallback(createUserCallbackInfo.resultCode, createUserCallbackInfo.localUserId));
                return;
            }
            doHandleConnectCallback(loginCallbackInfo.resultCode, loginCallbackInfo.localUserId);
        });
    }

    private void doHandleConnectCallback(int resultCode, EOS.ProductUserId localUserId) {
        try {
            EOS.throwIfErrorCode(resultCode);
        } catch (EOSException e) {
            Gdx.app.error("EpicPlatformManager", "EOS Connect callback failed", e);
            loginState = LoginState.FAILED;
            return;
        }
        try {
            connectToken = eosConnect.copyIdToken(localUserId);
        } catch (EOSException e) {
            Gdx.app.error("EpicPlatformManager", "Failed to copy Connect token", e);
            loginState = LoginState.FAILED;
            return;
        }
        Gdx.app.log("EpicPlatformManager", "EOS Connect successful");
        loginState = LoginState.SUCCEEDED;
        eosConnect.addNotifyAuthExpiration(data -> {
            Gdx.app.log("EpicPlatformManager", "Connect token expired; refreshing");
            doConnectLogin();
        });
        this.platformStatsHandle = new EpicPlatformStatsHandle(eosStats, eosAchievements, localUserId);
    }
```

> It is also unclear where the EOSSDK-Win64-Shipping.dll should be placed, Library.loadSystem("com.bearwaves.eos4j", "EOSSDK-Win64-Shipping"); is unable to find the .dll file no matter where I put it...

Per the README, they need to be on your classpath. How you do that is somewhat dependent on your build system and project setup. If like me you use Gradle, you might want something like this:

```gradle
sourceSets.main.resources.srcDirs += "EOS/SDK/Bin"
```

Hope this helps!

**Comment by dkoding** [comment]
Thank you! Will try this tonight.

EDIT: Although the game now found and loaded the correct libraries, I still get a 

`[EpicPlatformManager] Failed to get EOS Connect handle
com.bearwaves.eos4j.EOSException: Failed to create platform handle
	at com.bearwaves.eos4j.EOSPlatform.<init>(EOSPlatform.java:10)`

Any chance you could provide error messages with a little bit more information? I have provided 

```
eosPlatform = new EOSPlatform(new EOSPlatform.Options(
                    EPIC_PRODUCT_ID,
                    EPIC_SANDBOX_ID_DEV,
                    EPIC_DEPLOYMENT_ID_DEV,
                    EPIC_CLIENT_ID,
                    EPIC_CLIENT_SECRET,
                    EOSPlatform.Flag.DISABLE_OVERLAY.getValue()
            ));
```
as parameters, where the ID's match the ID's from the Epic Product settings page here : https://dev.epicgames.com/portal/en-US/dkit-as/products/my_game/settings/sdk-download-and-credentials

I use [EOS-SDK-27379709-v1.16.1.zip](https://eos-sdk.on.epicgames.com/562_EOS-SDK-27379709-v1.16.1.zip) - may there be some compatibility problem?

**Comment by JoelOtter** [comment]
Hello, sorry, I missed your edit to this comment. I've started creating a minimal example over at https://github.com/Bearwaves/eos4j-sample. I'll create a separate issue to investigate 1.16 compatibility. I recommend turning on verbose logging in the SDK; you can see how to do that in the sample.

**Comment by JoelOtter** [comment]
I checked v1.16 compatibility (#5) and it's fine, no issues.
