### ISSUE TITLE
Leaderboards support

### ISSUE THREAD

**Issue by codewalkerdan** [Bearwaves/eos4j#4]
Hello,

Are there plans to add Leaderboards support for eos4j?. My game is score based and I wondered if they are in the roadmap

**Comment by JoelOtter** [comment]
Hi! Yep, this was planned, and since you're asking for it I'll move it right to the top of the priorities. Thanks!

**Comment by codewalkerdan** [comment]
Thank you very much

**Comment by JoelOtter** [comment]
Hello, this has been implemented in v1.1.0 :)

**Comment by codewalkerdan** [comment]
Thank you!.. Will check it out right away! 👍
