### ISSUE TITLE
Enhancement: Ecom interface?

### ISSUE THREAD

**Issue by noblemaster** [Bearwaves/eos4j#7]
This is a great library! I tried login & achievement functionality, which works great.

Anyhow, are there any plans to implement the Ecom interface? It supports in-app purchasing & ownership validation? I don't mind helping out, I just don't know anything about the JNI side of things. I can help test it. 

I'm refering to this: https://dev.epicgames.com/docs/epic-games-store/services/ecom/ecom-overview

**Comment by JoelOtter** [comment]
Hey there :) Thanks for your kind words! Yes, I can absolutely implement Ecom; the only reason I haven't yet is I'm not using it for Feud. What are your timelines like in terms of when you'd need this?

**Comment by noblemaster** [comment]
Thanks for the response! I was hoping in the next 2 weeks or so if possible. This is probably going to take longer though?

I could probably come up with the Java code side (empty methods & relevant classes) matching what you already did, but not at all familiar with the C-side of the code, i.e. the `*Native classes`. I don't think everything is needed. I would be thinking (a) purchasing items, (2) purchase tokens for server side-validation and (3) retrieving purchased items for a user.

Not sure how much time you have? I could create a pull request with the relevant Java side?

**Comment by JoelOtter** [comment]
Ah don’t worry about it - I should be able to turn this around by then. Might need your help testing it!

**Comment by noblemaster** [comment]
Great! Yes, I would be happy to test. 😄

**Comment by JoelOtter** [comment]
In-progress at #8. Seems to be working so far though I'm going to struggle to test this myself as the overlay still doesn't work on macOS.

**Comment by JoelOtter** [comment]
Pushing WIP to main so you can start using it- catalog query is in now, use 1.2.0-SNAPSHOT if you'd like to try it!

**Comment by noblemaster** [comment]
Wow, that's very quick! 😄  I don't have time today/tomorrow, but will test it starting Thursday! 

To test out purchasing, I would need the following also something like. I would need the token, not sure if I need just one method? Also

- EOS_Ecom_Checkout
- EOS_Ecom_RedeemEntitlements: maybe needed for some to redeem?
- EOS_Ecom_Entitlement_Release: needed?
- EOS_Ecom_CopyTransactionById?
- EOS_Ecom_QueryOwnershipToken?
- EOS_Ecom_QueryEntitlementToken?

The explanation on https://dev.epicgames.com/docs/epic-games-store/services/ecom/ecom-overview is not 100% what is really needed to query existing purchases and obtain server-side verification tokens? It's clear when I implement it, but not sure at the moment.

**Comment by JoelOtter** [comment]
Honestly I've not used EOS's Ecom stuff for a few years (I did it for [Scavengers](https://store.steampowered.com/agecheck/app/1183940/)) so can't quite remember exactly how the flow works. I should be able to implement these pretty quickly though, just testing them might be slightly trickier.

**Comment by noblemaster** [comment]
Yes, it's sometimes a trial & error to figure out e.g. which ID goes where. I did the same for Google Play, iOS, Steam and Stripe, so it's more of a matter to get it done.

**Comment by JoelOtter** [comment]
Just to check - are you planning on using the `RedeemEntitlements` function from the client, or are you doing this using the web API on your server with an Entitlement Token?

Progress-wise, I've now added ownership and entitlement querying, plus tokens for both of those. The last bit is the Checkout/Transaction stuff, which may be tricker for me to test without an overlay but I'll do my best. I'm probably not going to bother with RedeemEntitlements until someone tells me they need it as Epic themselves recommend against doing that client-side.

**Comment by noblemaster** [comment]
I saw your updates. I was trying to download the latest 1.2.0-SNAPSHOT earlier today, but Sonatype was down! Anyhow, I can test the overlay easily, it's not problem at all :)

re-`RedeemEntitlements`: I'm verifying the token on the server and store the result in the database. That said, I would still prefer to _redeem the entitlement in the client if possible_ (after it's stored in the DB)? That way it matches what one have to do on e.g. for Google Play (redeemed in client after it's confirmed on the server side). It's not a problem regarding security, just makes the flow easier. That said, it's not so important, if you'd rather not implement it.

**Comment by JoelOtter** [comment]
Sure, no problem - will add it in :)

**Comment by noblemaster** [comment]
I got the popup to show! 😄 

To get the server-side verification working, I would methods to convert the transaction ID to the entitlement info. I believe the following methods are relevant(?). Basically the same as `queryEntitlements` but with the transaction ID as parameter!

- EOS_Ecom_CopyTransactionById 
- EOS_Ecom_Transaction_GetEntitlementsCount 
- EOS_Ecom_Transaction_CopyEntitlementByIndex 
- EOS_Ecom_Entitlement_Release (?).

![image](https://github.com/Bearwaves/eos4j/assets/2363626/300a772d-2cd5-40f2-97d7-e6d5c5dfd735)

**Comment by JoelOtter** [comment]
Hooray! Fabulous news. Yes I need to get the transaction stuff in - this is the bit I really can’t test myself as it’s impossible for me to actually _get_ a transaction, so I might have to get you to test a few iterations!

Entitlement release should be in already - in eos4j release is always a method on the object

**Comment by noblemaster** [comment]
Yes, I can test that out easily! 😃 

I was able to get the server-side entitlement verification to work too. It took some trial & error because the Epic documentation isn't very clear. Basically, each offer has 2 IDs and they appear to be both required:

- **Offer ID**: this is the ID to do a "checkout", i.e. to show the popup.
- **Audience Item ID** (also called **Catalog Item ID**): this will be the ID that is returned for entitlements (e.g. purchases). Not sure why it's called "Audience" in the EPIC UI but "Catalog" in the SDK? It appears to be the same.

I would probably add it somewhere to the documentation, in case other developers get confused?

Example:
![image](https://github.com/Bearwaves/eos4j/assets/2363626/48aae0e5-d4de-4efb-b16f-5c2a4c62b3f7)

**Comment by JoelOtter** [comment]
Thanks for the tip - honestly I think it's on Epic to document that. Perhaps make a note on their forums? :)

As for eos4j - transaction stuff is in now. I _think_ you should now have everything to do a full purchase flow. The transaction stuff builds OK but I've no idea if it actually works, would you mind giving it a test? Including the getTransactionId if possible, I know you don't need it but would be good to know it works!

**Comment by noblemaster** [comment]
I just tested it out: transactions IDs work perfectly fine! 😄 

Thanks for all the help! Very well done as I had no problems getting it working at all. Much appreciated!

**Comment by JoelOtter** [comment]
Ace, thanks for your help! I'll get this bundled up into a release once I've updated the example app.

**Comment by noblemaster** [comment]
No, all the thanks go to you! This was very quick and working flawlessly at the same time. 😄

**Comment by JoelOtter** [comment]
Hey @noblemaster, I just saw a bunch of your games come up on the Epic new releases (I was looking for my game and spotted Retro Commander right next to it!). How would you feel about those of them that use eos4j being added to the front page of this repo? Obviously no worries at all if you'd prefer not to!

**Comment by noblemaster** [comment]
@JoelOtter Yes, that would be nice! You can obtain the assets here: https://www.noblemaster.com/press/index.php

It's just the following 3 games: (1) Age of Conquest IV, (2) Retro Commander and (3) Demise of Nations!

**Comment by JoelOtter** [comment]
> @JoelOtter Yes, that would be nice! You can obtain the assets here: https://www.noblemaster.com/press/index.php
> 
> It's just the following 3 games: (1) Age of Conquest IV, (2) Retro Commander and (3) Demise of Nations!

Fab, thank you! I'll link to their Epic store pages of course :)
